framework:
    default_locale: 'en'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'


#framework:
##    default_locale: '%locale%'
#default_locale: 'fr'
#    translator:
#        paths:
#            - '%kernel.project_dir%/translations'
#        #        default_path:
#        #            - '%kernel.project_dir%/translations'
#        fallbacks:
#            - '%locale%'
