#vich_uploader:
#    db_driver: orm
#
#    mappings:
#        products:
##            uri_prefix: /images/products
#            uri_prefix: /images
#            #            upload_destination: '%kernel.project_dir%/public/images/products'
#            upload_destination: '%kernel.project_dir%/public/images'
#            # Decide how uploaded files would be renamed
#            namer: Vich\UloaderBundle\UniqidNamer
